//LOGIN
export const ADD_LOGIN = "ADD_LOGIN";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const REMOVE_LOGIN = "REMOVE_LOGIN";

//Sign up
export const ADD_SIGNUP = "ADD_SIGNUP";
export const SIGNUP_LOADING = "SIGNUP_LOADING";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const REMOVE_SIGNUP = "REMOVE_SIGNUP";

// VENDOR actionsTypes

export const VENDOR_GET_DATA = "VENDOR_GET_DATA";
export const VENDOR_SET_DATA = "VENDOR_SET_DATA";
export const VENDOR_FAIL_DATA = "VENDOR_FAIL_DATA";
export const DELETE_VENDOR_FAIL = "DELETE_VENDOR_FAIL";
export const POST_VENDOR_DATA = "POST_VENDOR_DATA";
export const POST_VENDOR_DATA_START = "POST_VENDOR_DATA_START";
export const POST_VENDOR_DATA_FAIL = "POST_VENDOR_DATA_FAIL";
export const EDIT_VENDOR_ROW_START = "EDIT_VENDOR_ROW_START";
export const EDIT_VENDOR_SET_DATA = "EDIT_VENDOR_SET_DATA";

export const FAIL_EDIT_VENDOR = "FAIL_EDIT_VENDOR";
export const CURRENT_USER_EDIT_VENDOR = "CURRENT_USER_EDIT_VENDOR";
export const UPDATE_VENDOR_DATA_START = "UPDATE_VENDOR_DATA_START";

// Transactions actionTypes

export const TRANSACTION_GET_DATA = "TRANSACTION_GET_DATA";
export const TRANSACTION_SET_DATA = "TRANSACTION_SET_DATA";
export const TRANSACTION_FAIL_DATA = "TRANSACTION_FAIL_DATA";
export const DELETE_TRANSACTION_FAIL = "DELETE_TRANSACTION_FAIL";
export const POST_TRANSACTION_DATA = "POST_TRANSACTION_DATA";
export const POST_TRANSACTION_DATA_START = "POST_TRANSACTION_DATA_START";
export const POST_TRANSACTION_DATA_FAIL = "POST_TRANSACTION_DATA_FAIL";
export const POST_TRANSACTION_DATA_SUCCESS = "POST_TRANSACTION_DATA_SUCCESS";
export const EDIT_TRANSACTION_ROW_START = "EDIT_TRANSACTION_ROW_START";

export const FAIL_EDIT_TRANSACTION = "FAIL_EDIT_TRANSACTION";
export const CURRENT_USER_EDIT_TRANSACTION = "CURRENT_USER_EDIT_TRANSACTION";
export const UPDATE_TRANSACTION_DATA_START = "UPDATE_TRANSACTION_DATA_START";

// Customer actionTypes

export const CUSTOMER_GET_DATA = "CUSTOMER_GET_DATA";
export const CUSTOMER_SET_DATA = "CUSTOMER_SET_DATA";
export const CUSTOMER_FAIL_DATA = "CUSTOMER_FAIL_DATA";
export const DELETE_CUSTOMER_FAIL = "DELETE_CUSTOMER_FAIL";
export const POST_CUSTOMER_DATA = "POST_CUSTOMER_DATA";
export const POST_CUSTOMER_DATA_START = "POST_CUSTOMER_DATA_START";
export const POST_CUSTOMER_DATA_FAIL = "POST_CUSTOMER_DATA_FAIL";
export const POST_CUSTOMER_DATA_SUCCESS = "POST_CUSTOMER_DATA_SUCCESS";
export const EDIT_CUSTOMER_ROW_START = "EDIT_CUSTOMER_ROW_START";

export const FAIL_EDIT_CUSTOMER = "FAIL_EDIT_CUSTOMER";
export const CURRENT_USER_EDIT_CUSTOMER = "CURRENT_USER_EDIT_CUSTOMER";
export const UPDATE_CUSTOMER_DATA_START = "UPDATE_CUSTOMER_DATA_START";

// Category actionTypes

export const CATEGORY_GET_DATA = "CATEGORY_GET_DATA";
export const CATEGORY_SET_DATA = "CATEGORY_SET_DATA";
export const CATEGORY_FAIL_DATA = "CATEGORY_FAIL_DATA";
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL";
export const POST_CATEGORY_DATA = "POST_CATEGORY_DATA";
export const POST_CATEGORY_DATA_START = "POST_CATEGORY_DATA_START";
export const POST_CATEGORY_DATA_FAIL = "POST_CATEGORY_DATA_FAIL";
export const POST_CATEGORY_DATA_SUCCESS = "POST_CATEGORY_DATA_SUCCESS";
export const EDIT_CATEGORY_ROW_START = "EDIT_CATEGORY_ROW_START";

export const FAIL_EDIT_CATEGORY = "FAIL_EDIT_CATEGORY";
export const CURRENT_USER_EDIT_CATEGORY = "CURRENT_USER_EDIT_CATEGORY";
export const UPDATE_CATEGORY_DATA_START = "UPDATE_CATEGORY_DATA_START";

// VENDOR  Type actionsTypes

export const VENDORTYPE_GET_DATA = "VENDORTYPE_GET_DATA";
export const VENDORTYPE_SET_DATA = "VENDORTYPE_SET_DATA";
export const VENDORTYPE_FAIL_DATA = "VENDORTYPE_FAIL_DATA";
export const DELETE_VENDORTYPE_FAIL = "DELETE_VENDORTYPE_FAIL";
export const POST_VENDORTYPE_DATA = "POST_VENDORTYPE_DATA";
export const POST_VENDORTYPE_DATA_START = "POST_VENDORTYPE_DATA_START";
export const POST_VENDORTYPE_DATA_FAIL = "POST_VENDORTYPE_DATA_FAIL";
export const EDIT_VENDORTYPE_ROW_START = "EDIT_VENDORTYPE_ROW_START";

export const FAIL_EDIT_VENDORTYPE = "FAIL_EDIT_VENDORTYPE";
export const CURRENT_USER_EDIT_VENDORTYPE = "CURRENT_USER_EDIT_VENDORTYPE";
export const UPDATE_VENDORTYPE_DATA_START = "UPDATE_VENDORTYPE_DATA_START";
